---
- name: Install prerequisite packages.
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - postgresql
      - postgresql-contrib
    state: latest
  notify: Enable PostgreSQL

- name: Create/edit postgresql config file /etc/postgresql/17/main/postgresql.conf
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/17/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: "u=rw,g=r,o=r"
  notify: Restart PostgreSQL
