---
- name: Copy sysctl file.
  ansible.builtin.copy:
    src: 70-ipv6.conf
    dest: /etc/sysctl.d/70-ipv6.conf

- name: Run sysctl -p to activate change in file.
  ansible.builtin.command: /usr/sbin/sysctl -p /etc/sysctl.d/70-ipv6.conf
