---
- name: Install redis-server packages.
  ansible.builtin.apt:
    pkg:
      - redis-server
    state: latest

- name: Create/edit redis configuration file /etc/redis/redis.conf.
  ansible.builtin.template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: "u=rw,g=r,o="

- name: Create/edit redis configuration file for systemd /lib/systemd/system/redis-server.service.
  ansible.builtin.template:
    src: systemd.service.j2
    dest: /lib/systemd/system/redis-server.service
    owner: root
    group: root
    mode: "u=rwx,g=r,o=r"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart redis service
  ansible.builtin.service:
    name: redis
    state: restarted
    enabled: true
