---
- name: Install dovecot packages.
  ansible.builtin.apt:
    pkg:
      - dovecot-core
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-mysql
    state: latest

- name: Ensure group vmail exists with correct gid.
  ansible.builtin.group:
    name: vmail
    state: present
    gid: 5000

- name: Add the user vmail.
  ansible.builtin.user:
    name: vmail
    shell: /sbin/nologin
    comment: vmail
    uid: 5000
    group: vmail
    home: /var/vmail
    create_home: false

- name: Create folder to store mail in.
  ansible.builtin.file:
    path: /var/mail
    state: directory
    owner: root
    group: vmail
    mode: "u=rwx,g=rwxs,o="

- name: Create/edit dovecot configuration file dovecot.conf.
  ansible.builtin.template:
    src: dovecot.conf.j2
    dest: /etc/dovecot.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Create/edit dovecot configuration file conf.d/10-logging.conf.
  ansible.builtin.template:
    src: 10-logging.conf.j2
    dest: /etc/dovecot/conf.d/10-logging.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Create/edit dovecot configuration file conf.d/10-mail.conf.
  ansible.builtin.template:
    src: 10-mail.conf.j2
    dest: /etc/dovecot/conf.d/10-mail.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Create/edit dovecot configuration file conf.d/10-auth.conf.
  ansible.builtin.template:
    src: 10-auth.conf.j2
    dest: /etc/dovecot/conf.d/10-auth.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Create/edit dovecot configuration file conf.d/auth-sql.ext.
  ansible.builtin.template:
    src: auth-sql.conf.ext.j2
    dest: /etc/dovecot/conf.d/auth-sql.conf.ext
    owner: dovecot
    group: dovecot
    mode: "u=rw,g=r,o="

- name: Create/edit dovecot configuration file dovecot-sql.ext.
  ansible.builtin.template:
    src: dovecot-sql.conf.ext.j2
    dest: /etc/dovecot/dovecot-sql.conf.ext
    owner: dovecot
    group: dovecot
    mode: "u=rw,g=r,o="

- name: Create/edit dovecot configuration file conf.d/10-master.conf.
  ansible.builtin.template:
    src: 10-master.conf.j2
    dest: /etc/dovecot/conf.d/10-master.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Create/edit dovecot configuration file conf.d/10-ssl.conf.
  ansible.builtin.template:
    src: 10-ssl.conf.j2
    dest: /etc/dovecot/conf.d/10-ssl.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Create/edit dovecot configuration file conf.d/10-mailcrypt.conf.
  ansible.builtin.template:
    src: 10-mailcrypt.conf.j2
    dest: /etc/dovecot/conf.d/10-mailcrypt.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Restart dovecot service
  ansible.builtin.service:
    name: dovecot
    state: restarted
    enabled: true
