---
- name: Install packages needed for web application ddmail_email_remover
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
      - python3-venv
    state: latest

- name: Install screen in dev
  ansible.builtin.apt:
    pkg:
      - screen
    state: latest
  when: env == "dev"

- name: Stat /opt/ddmail_email_remover folder
  ansible.builtin.stat:
    path: /opt/ddmail_email_remover
  register: ddmail_email_remover

- name: Move /opt/ddmail_email_remover folder
  ansible.builtin.command: mv /opt/ddmail_email_remover /opt/ddmail_email_remover_{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}
  when: ddmail_email_remover.stat.exists

- name: Create /opt/ddmail_email_remover if it does not exist
  ansible.builtin.file:
    path: /opt/ddmail_email_remover
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  when: env == "prod"

- name: Create /opt/ddmail_email_remover if it does not exist
  ansible.builtin.file:
    path: /opt/ddmail_email_remover
    state: directory
    owner: '{{ ddmail_email_remover_runas_user }}'
    group: '{{ ddmail_email_remover_runas_group }}'
    mode: "u=rwx,g=rx,o=rx"
  when: env == "dev"

- name: Clone ddmail_email_remover repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/drzobin/ddmail_email_remover.git
    dest: /opt/ddmail_email_remover/ddmail_email_remover
  when: env == "dev"

- name: Create ddmail_email_remover python venv.
  ansible.builtin.command: python3 -m venv /opt/ddmail_email_remover/venv

- name: Add the group "{{ ddmail_email_remover_runas_group }}"
  ansible.builtin.group:
    name: "{{ ddmail_email_remover_runas_group }}"
    state: present
  when: env == "prod"

- name: Add the user "{{ ddmail_email_remover_runas_user }}"
  ansible.builtin.user:
    name: "{{ ddmail_email_remover_runas_user }}"
    shell: /sbin/nologin
    create_home: false
    group: "{{ ddmail_email_remover_runas_group }}"
    state: present
  when: env == "prod"


- name: Install ddmail_email_remover and requirenments with pip.
  ansible.builtin.pip:
    name: ddmail-email-remover
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/ddmail_email_remover/venv
  when: env == "prod"

- name: Install requirenments for development with pip.
  ansible.builtin.pip:
    name: .[dev]
    chdir: /opt/ddmail_email_remover/ddmail_email_remover
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/ddmail_email_remover/venv
  when: env == "dev"

- name: Set user and group ownership of /opt/ddmail_email_remover
  ansible.builtin.file:
    state: directory
    recurse: true
    owner: "{{ ddmail_email_remover_user_owner }}"
    group: "{{ ddmail_email_remover_group_owner }}"
    path: /opt/ddmail_email_remover

- name: Set git remote for ddmail_email_remover
  ansible.builtin.shell: cd /opt/ddmail_email_remover/ddmail_email_remover; git remote set-url origin git@github.com:drzobin/ddmail_email_remover.git
  become: true
  become_method: su
  become_user: "{{ ddmail_email_remover_runas_user }}"
  when: env == "dev"

- name: Create /opt/ddmail_email_remover/config if it does not exist
  ansible.builtin.file:
    path: /opt/ddmail_email_remover/config
    state: directory
    owner: '{{ ddmail_email_remover_runas_user }}'
    group: '{{ ddmail_email_remover_runas_group }}'
    mode: "u=rwx,g=rx,o="


- name: Create/edit ddmail_email_remover config file /opt/ddmail_email_remover/config/config.toml
  ansible.builtin.template:
    src: config.toml.j2
    dest: /opt/ddmail_email_remover/config/config.toml
    owner: '{{ ddmail_email_remover_runas_user }}'
    group: '{{ ddmail_email_remover_runas_group }}'
    mode: "u=rw,g=r,o="


- name: Create/edit ddmail_email_remover gunicorne service configuration file /etc/systemd/system/ddmail_email_remover.service
  ansible.builtin.template:
    src: systemd_service.j2
    dest: /etc/systemd/system/ddmail_email_remover.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  when: env == "prod"

- name: Add logdir for gunicorn.
  ansible.builtin.file:
    path: /var/log/gunicorn
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  when: env == "prod"

- name: Add logdir for ddmail_email_remover gunicorn.
  ansible.builtin.file:
    path: /var/log/gunicorn/ddmail_email_remover.log
    state: touch
    owner: '{{ ddmail_email_remover_runas_user }}'
    group: '{{ ddmail_email_remover_runas_group }}'
    mode: u=rw,g=r,o=
  when: env == "prod"

- name: Add logdir for ddmail_email_remover.
  ansible.builtin.file:
    path: /var/log/ddmail_email_remover.log
    state: touch
    owner: '{{ ddmail_email_remover_runas_user }}'
    group: '{{ ddmail_email_remover_runas_group }}'
    mode: u=rw,g=r,o=

- name: Kill development server in screen.
  ansible.builtin.command: screen -X -S ddmail_email_remover quit
  become: true
  become_method: su
  become_user: "{{ ddmail_email_remover_runas_user }}"
  ignore_errors: true
  when: env == "dev"

- name: Wipe dead screen.
  ansible.builtin.command: screen -wipe
  become: true
  become_method: su
  become_user: "{{ ddmail_email_remover_runas_user }}"
  when: env == "dev"

- name: Create/edit ddmail_email_remover startup script for development
  ansible.builtin.template:
    src: run_dev.sh.j2
    dest: /opt/ddmail_email_remover/run_dev.sh
    owner: "{{ ddmail_email_remover_runas_user }}"
    group: "{{ ddmail_email_remover_runas_group }}"
    mode: "u=rwx,g=r,o=r"
  when: env == "dev"

- name: Start development server in screen.
  ansible.builtin.command: screen -S ddmail_email_remover -d -m bash -c "sleep 5; source /opt/ddmail_email_remover/run_dev.sh; /bin/bash"
  become: true
  become_method: su
  become_user: "{{ ddmail_email_remover_runas_user }}"
  when: env == "dev"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: env == "prod"

- name: Restart ddmail_email_remover gunicorn service
  ansible.builtin.service:
    name: ddmail_email_remover
    state: restarted
    enabled: true
  when: env == "prod"
