---
- name: Install dep package.
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - wget
      - gpg
    state: latest

- name: Get purplei2p gpg key..
  ansible.builtin.shell: wget -q -O- https://repo.i2pd.xyz/r4sas.gpg | gpg --dearmor > /usr/share/keyrings/purplei2p.gpg

- name: Add purplei2p apt signing key.
  ansible.builtin.apt_key:
    file: /usr/share/keyrings/purplei2p.gpg
    state: present

- name: Add purplei2p apt repository.
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/purplei2p.gpg] https://repo.i2pd.xyz/debian bookworm main"
    state: present
    filename: purplei2p
    update_cache: true

- name: Add purplei2p src apt repository.
  ansible.builtin.apt_repository:
    repo: "deb-src [signed-by=/usr/share/keyrings/purplei2p.gpg] https://repo.i2pd.xyz/debian bookworm main"
    state: present
    filename: purplei2p
    update_cache: true

- name: Run "apt-get update".
  ansible.builtin.apt:
    update_cache: true

- name: Install latest version of i2pd ignoring "install-recommends".
  ansible.builtin.apt:
    name: i2pd
    state: latest
    install_recommends: false
    update_cache: true

- name: Create/edit i2pd configuration file /etc/i2pd/i2pd.conf
  ansible.builtin.template:
    src: i2pd.conf.j2
    dest: /etc/i2pd/i2pd.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Create/edit i2pd tunnels configuration file /etc/i2pd/tunnels.conf
  ansible.builtin.template:
    src: tunnels.conf.j2
    dest: /etc/i2pd/tunnels.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Set i2p hostname/b32 address for ddmail_webapp in prod
  ansible.builtin.shell: echo "$(head -c 391 /var/lib/i2pd/ddmail_key.dat | sha256sum | cut -f1 -d\  | xxd -r -p | base32 | tr '[:upper:]' '[:lower:]' | sed -r 's/=//g').b32.i2p" > /opt/ddmail_webapp_venv/ddmail/ddmail/templates/i2p_hostname
  when: env == "prod"

- name: Set i2p hostname/b32 address for ddmail_webapp in dev
  ansible.builtin.shell: echo "$(head -c 391 /var/lib/i2pd/ddmail_key.dat | sha256sum | cut -f1 -d\  | xxd -r -p | base32 | tr '[:upper:]' '[:lower:]' | sed -r 's/=//g').b32.i2p" > /opt/ddmail_webapp_venv/ddmail_webapp/ddmail/ddmail/templates/i2p_hostname
  when: env == "dev"

- name: Restart i2pd service
  ansible.builtin.service:
    name: i2pd
    state: restarted
    enabled: true
