---
- name: Setting up mail server
  hosts: mail_server
  become: true
  become_user: root
  become_method: ansible.builtin.su
  become_flags: '-'

  roles:
    - general_packages
    - disable_ipv6
    - nftables
    - sshd
    - unattended-upgrades
    - mariadb
    - mailsystem_db
    - self_signed_certs
    - rspamd
    - redis
    - postfix
    - dovecot
    - apache2
    - ddmail_webapp
    - ddmail_email_remover
    - github
