---
- name: Setting up mail server
  hosts: mail_server
  become: true
  become_user: root
  become_method: su

  roles:
              - general_packages
              - disable_ipv6
              - nftables
              - sshd
              - mariadb
              - mailsystem_db
              - www_ddmail_se
