---
- name: Setting up primary server for ddmail system in dev.
  hosts: primary_srv
  become: true
  become_user: root
  become_method: ansible.builtin.su
  become_flags: "-"

  roles:
    - general_packages
    - disable_ipv6
    - nftables
    - inaccessible_dirs
    - bind
    - set_nameserver
    - sshd
    - rsyslog
    - unattended-upgrades
    - sysstat
    - mariadb
    - mailsystem_db
    - self_signed_certs
    - redis
    - olefy
    - clamav
    - rspamd
    - postfix
    - dovecot
    - apache2
    - doas
    - ddmail_webapp
    - ddmail_email_remover
    - ddmail_dmcp_keyhandler
    - ddmail_openpgp_keyhandler
    - ddmail_openpgp_encryptor
    - ddmail_backup_taker
    - ddmail_backup_receiver
    - ddmail_validators
    - github
