---
- name: Setting up mail server
  hosts: mail_server
  become: true
  become_user: root
  become_method: ansible.builtin.su

  roles:
    - general_packages
    - disable_ipv6
    - nftables
    - sshd
    - unattended-upgrades
    - unbound
    - certbot
    - mariadb
    - mailsystem_db
    - redis
    - rspamd
    - postfix
    - dovecot
    - apache2
    - www_ddmail_se
