---
- name: Setting up secondary server for ddmail system in prod.
  hosts: secondary_srv
  become: true
  become_user: root
  become_method: ansible.builtin.su
  become_flags: "-"

  roles:
    - general_packages
    - disable_ipv6
    - nftables
    - nebula
    - sshd
    - rsyslog
    - unattended-upgrades
    - unbound
    - set_nameserver
    - sysstat
    - ddmail_backup_receiver
    - caddy
