---
- name: Setting up mail server
  hosts: mail_server
  become: true
  become_user: root
  become_method: ansible.builtin.su
  become_flags: "-"

  roles:
    - general_packages
    - disable_ipv6
    - inaccessible_dirs
    - nftables
    - sshd
    - rsyslog
    - unattended-upgrades
    - unbound
    - set_nameserver
    - certbot
    - mariadb
    - mailsystem_db
    - redis
    - olefy
    - clamav
    - rspamd
    - postfix
    - dovecot
    - doas
    - ddmail_webapp
    - ddmail_email_remover
    - ddmail_dmcp_keyhandler
    - ddmail_openpgp_keyhandler
    - ddmail_openpgp_encryptor
    - apache2
    - tor_onion_service
    - i2pd
    - ddmail_backup
