---
- name: Install packages needed for web application ddmail
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
      - python3-venv
    state: latest

- name: Install screen in dev
  ansible.builtin.apt:
    pkg:
      - screen
    state: latest
  when: env == "dev"

- name: Stat /opt/ddmail_dmcp_keyhandler_venv folder
  ansible.builtin.stat:
    path: /opt/ddmail_dmcp_keyhandler_venv
  register: ddmail_dmcp_keyhandler_venv

- name: Move /opt/ddmail_dmcp_keyhandler_venv folder
  ansible.builtin.command: mv /opt/ddmail_dmcp_keyhandler_venv /opt/ddmail_dmcp_keyhandler_venv_{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}
  when: ddmail_dmcp_keyhandler_venv.stat.exists

- name: Create ddmail_dmcp_keyhandler python env.
  ansible.builtin.command: python3 -m venv /opt/ddmail_dmcp_keyhandler_venv

- name: Add the group "{{ ddmail_dmcp_keyhandler_gunicorn_group }}"
  ansible.builtin.group:
    name: "{{ ddmail_dmcp_keyhandler_gunicorn_group }}"
    state: present
  when: env == "prod"

- name: Add the user "{{ ddmail_dmcp_keyhandler_gunicorn_user }}"
  ansible.builtin.user:
    name: "{{ ddmail_dmcp_keyhandler_gunicorn_user }}"
    shell: /sbin/nologin
    create_home: false
    group: "{{ ddmail_dmcp_keyhandler_gunicorn_group }}"
    state: present
  when: env == "prod"

- name: Clone ddmail_dmcp_keyhandler repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/drzobin/ddmail_dmcp_keyhandler.git
    dest: /opt/ddmail_dmcp_keyhandler_venv/ddmail_dmcp_keyhandler

- name: Stat ddmail_dmcp_keyhandler folder
  ansible.builtin.stat:
    path: /opt/ddmail_dmcp_keyhandler_venv/ddmail_dmcp_keyhandler
  register: ddmail_dmcp_keyhandler

- name: Move dmcp_keyhandler from ddmail_dmcp_keyhandler
  ansible.builtin.command: mv /opt/ddmail_dmcp_keyhandler_venv/ddmail_dmcp_keyhandler/dmcp_keyhandler /opt/ddmail_dmcp_keyhandler_venv/
  when:
    - ddmail_dmcp_keyhandler.stat.exists
    - env == "prod"

- name: Remove ddmail_dmcp_keyhandler folder
  ansible.builtin.command: rm -rf /opt/ddmail_dmcp_keyhandler_venv/ddmail_dmcp_keyhandler
  when:
    - ddmail_dmcp_keyhandler.stat.exists
    - env == "prod"

- name: Install requirenments with pip.
  ansible.builtin.pip:
    requirements: /opt/ddmail_dmcp_keyhandler_venv/dmcp_keyhandler/requirements.txt
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/ddmail_dmcp_keyhandler_venv
  when: env == "prod"

- name: Install requirenments with pip.
  ansible.builtin.pip:
    requirements: /opt/ddmail_dmcp_keyhandler_venv/ddmail_dmcp_keyhandler/dmcp_keyhandler/requirements.txt
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/ddmail_dmcp_keyhandler_venv
  when: env == "dev"

- name: Set user and group ownership of /opt/ddmail_dmcp_keyhandler_venv
  ansible.builtin.file:
    state: directory
    recurse: true
    owner: "{{ ddmail_dmcp_keyhandler_venv_user_owner }}"
    group: "{{ ddmail_dmcp_keyhandler_venv_group_owner }}"
    path: /opt/ddmail_dmcp_keyhandler_venv

- name: Set git remote for ddmail_dmcp_keyhandler
  ansible.builtin.shell: cd /opt/ddmail_dmcp_keyhandler_venv/ddmail_dmcp_keyhandler; git remote set-url origin git@github.com:drzobin/ddmail_dmcp_keyhandler.git
  become: true
  become_method: su
  become_user: "{{ ddmail_dmcp_keyhandler_runas_user }}"
  when: env == "dev"

- name: Create/edit ddmail_dmcp_keyhandler config file /opt/ddmail_dmcp_keyhandler_venv/dmcp_keyhandler/config.py
  ansible.builtin.template:
    src: config.py.j2
    dest: /opt/ddmail_dmcp_keyhandler_venv/dmcp_keyhandler/config.py
    owner: '{{ ddmail_dmcp_keyhandler_gunicorn_user }}'
    group: '{{ ddmail_dmcp_keyhandler_gunicorn_group }}'
    mode: "u=rw,g=r,o="
  when: env == "prod"

- name: Create/edit ddmail_dmcp_keyhandler config file /opt/ddmail_dmcp_keyhandler_venv/ddmail_dmcp_keyhandler/dmcp_keyhandler/config.py
  ansible.builtin.template:
    src: config.py.j2
    dest: /opt/ddmail_dmcp_keyhandler_venv/ddmail_dmcp_keyhandler/dmcp_keyhandler/config.py
    owner: "{{ ddmail_dmcp_keyhandler_venv_user_owner }}"
    group: "{{ ddmail_dmcp_keyhandler_venv_group_owner }}"
    mode: "u=rw,g=r,o=r"
  when: env == "dev"

- name: Install ddmail_dmcp_keyhandler webapp with pip
  ansible.builtin.pip:
    name: /opt/ddmail_dmcp_keyhandler_venv/dmcp_keyhandler
    extra_args: -e
    virtualenv_python: python3
    virtualenv: /opt/ddmail_dmcp_keyhandler_venv
  when: env == "prod"

- name: Create/edit ddmail_dmcp_keyhandler gunicorne service configuration file /etc/systemd/system/dmcp_keyhandler.service
  ansible.builtin.template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/dmcp_keyhandler.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  when: env == "prod"

- name: Add logdir for gunicorn.
  ansible.builtin.file:
    path: /var/log/gunicorn
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  when: env == "prod"

- name: Add logfile for ddmail_dmcp_keyhandler gunicorn.
  ansible.builtin.file:
    path: /var/log/gunicorn/ddmail_dmcp_keyhandler.log
    state: touch
    owner: '{{ ddmail_dmcp_keyhandler_gunicorn_user }}'
    group: '{{ ddmail_dmcp_keyhandler_gunicorn_group }}'
    mode: u=rw,g=r,o=
  when: env == "prod"

- name: Add logfile for ddmail_dmcp_keyhandler.
  ansible.builtin.file:
    path: /var/log/ddmail_dmcp_keyhandler.log
    state: touch
    owner: '{{ ddmail_dmcp_keyhandler_gunicorn_user }}'
    group: '{{ ddmail_dmcp_keyhandler_gunicorn_group }}'
    mode: u=rw,g=r,o=
  when: env == "prod"

- name: Add logfile for ddmail_dmcp_keyhandler.
  ansible.builtin.file:
    path: /var/log/ddmail_dmcp_keyhandler.log
    state: touch
    owner: '{{ ddmail_dmcp_keyhandler_runas_user }}'
    group: '{{ ddmail_dmcp_keyhandler_runas_user }}'
    mode: u=rw,g=r,o=
  when: env == "dev"

- name: Kill development server in screen.
  ansible.builtin.command: screen -X -S ddmail_dmcp_keyhandler kill
  become: true
  become_method: su
  become_user: "{{ ddmail_dmcp_keyhandler_runas_user }}"
  ignore_errors: true
  when: env == "dev"

- name: Start development server in screen.
  ansible.builtin.command: screen -S ddmail_dmcp_keyhandler -d -m bash -c "sleep 5; source /opt/ddmail_dmcp_keyhandler_venv/bin/activate; cd /opt/ddmail_dmcp_keyhandler_venv/ddmail_dmcp_keyhandler/dmcp_keyhandler; export MODE=DEVELOPMENT; flask --app dmcp_keyhandler:create_app run --host=127.0.0.1 --port 8002 --debug; /bin/bash"
  become: true
  become_method: su
  become_user: "{{ ddmail_dmcp_keyhandler_runas_user }}"
  when: env == "dev"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: env == "prod"

- name: Restart dmcp_keyhandler gunicorn service
  ansible.builtin.service:
    name: dmcp_keyhandler
    state: restarted
    enabled: true
  when: env == "prod"
