---
- name: Install unattended-upgrades package.
  apt:
    pkg:
      - unattended-upgrades
      - apt-listchanges
    state: latest

- name: Create/edit unattended-upgrades configuration file /etc/apt/apt.conf.d/50unattended-upgrades.
  template: src=50unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades

- name: Activate unattended-upgrades step one.
  command: echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections

- name: Activate unattended-upgrades step two.
  command: dpkg-reconfigure -f noninteractive unattended-upgrades
