---
- name: Install unattended-upgrades package.
  ansible.builtin.apt:
    pkg:
      - unattended-upgrades
      - apt-listchanges
    state: latest

- name: Create/edit unattended-upgrades configuration file /etc/apt/apt.conf.d/50unattended-upgrades.
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Runs echo "unattended-upgrades unattended-upgrades/enable_auto_updates boolean true" | debconf-set-selections
  ansible.builtin.debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    vtype: boolean
    value: "true"

- name: Runs dpkg-reconfigure -f noninteractive unattended-upgrades
  ansible.builtin.command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
    creates: /etc/apt/apt.conf.d/20auto-upgrades
