---
- name: Install packages needed for web application ddmail
  apt:
    pkg:
      - apache2
      - apache2-utils
      - libapache2-mod-evasive
    state: latest

- name: Enable apache2 mod proxy
  ansible.builtin.command: /usr/sbin/a2enmod proxy

- name: Enable apache2 mod proxy_http
  ansible.builtin.command: /usr/sbin/a2enmod proxy_http

- name: Enable apache2 mod ssl
  ansible.builtin.command: /usr/sbin/a2enmod ssl
  when: env == "prod"

- name: Enable apache2 mod evasive
  ansible.builtin.command: /usr/sbin/a2enmod evasive
  when: env == "prod"

- name: Enable apache2 mod headers
  ansible.builtin.command: /usr/sbin/a2enmod headers

- name: Remove server information by edit /etc/apache2/conf-available/security.conf
  template: src=security.conf.j2 dest=/etc/apache2/conf-available/security.conf

- name: Hardening apache2 systemd unit config with namespaces and seccomp /lib/systemd/system/apache2.service
  template: src=apache2.service.j2 dest=/lib/systemd/system/apache2.service

- name: Create/edit apache2 config file /etc/apache2/mods-available/evasive.conf using template evasive.conf.j2
  template: src=evasive.conf.j2 dest=/etc/apache2/mods-available/evasive.conf
  when: env == "prod"

- name: Create/edit apache2 config file /etc/apache2/sites-available/000-default.conf using template 000-default.conf-prod.j2
  template: src=000-default.conf-prod.j2 dest=/etc/apache2/sites-available/000-default.conf
  when: env == "prod"

- name: Create/edit apache2 config file /etc/apache2/sites-available/000-default.conf using template 000-default.conf-dev.j2
  template: src=000-default.conf-dev.j2 dest=/etc/apache2/sites-available/000-default.conf
  when: env == "dev"

- name: Create/edit apache2 config file /etc/apache2/sites-available/001-default-ssl.conf
  template: src=001-default-ssl.conf.j2 dest=/etc/apache2/sites-available/001-default-ssl.conf
  when: env == "prod"

- name: Create/edit apache2 config file /etc/apache2/mods-available/ssl.conf
  template: src=ssl.conf.j2 dest=/etc/apache2/mods-available/ssl.conf
  when: env == "prod"

- name: Enable apache2 site 001-default-ssl.conf
  ansible.builtin.command: /usr/sbin/a2ensite 001-default-ssl.conf
  when: env == "prod"

- name: Reload systemd
  command: systemctl daemon-reload

- name: Restar apache2 service
  service: name=apache2 state=restarted enabled=yes
