---
- name: Install unbound packages.
  ansible.builtin.apt:
    pkg:
      - unbound
    state: latest

- name: Create/edit unbound configuration file /etc/unbound/unbound.conf.d/unbound.conf
  ansible.builtin.template:
    src: etc_unbound_unbound.conf.d_unbound.conf.j2
    dest: /etc/unbound/unbound.conf.d/unbound.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Restart unbound service
  ansible.builtin.service:
    name: unbound
    state: restarted
    enabled: true
