---
- name: Install dep package.
  ansible.builtin.apt:
    pkg:
      - gpg
      - apt-transport-https
    state: latest

- name: Add caddy apt signing key.
  ansible.builtin.apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    state: present

- name: Add caddy apt repository.
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://dl.cloudsmith.io/public/caddy/stable/deb/debian bookworm main"
    state: present
    filename: caddy
    update_cache: true

- name: Run "apt-get update".
  ansible.builtin.apt:
    update_cache: true

- name: Install latest version of caddy ignoring "install-recommends".
  ansible.builtin.apt:
    name: caddy
    state: latest
    install_recommends: false
    update_cache: true

- name: Create/edit caddy configuration file /etc/caddy/Caddyfile.
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Restart caddy service.
  ansible.builtin.service:
    name: caddy
    state: restarted
    enabled: true
