---
- name: Install prerequisite packages.
  ansible.builtin.apt:
    pkg:
      - gpg
      - apt-transport-https
      - curl
      - debian-keyring
    state: latest

- name: Download and dearmor Caddy GPG key
  ansible.builtin.shell: >
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

- name: Download Caddy repository list configuration
  ansible.builtin.shell: >
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
  args:
    creates: /etc/apt/sources.list.d/caddy-stable.list

- name: Ensure correct read permissions for keyring and source list
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0644'
  loop:
    - /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    - /etc/apt/sources.list.d/caddy-stable.list

- name: Install latest version of caddy ignoring "install-recommends".
  ansible.builtin.apt:
    name: caddy
    state: latest
    install_recommends: false

- name: Create/edit caddy configuration file /etc/caddy/Caddyfile.
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Ensure Caddy certs directory exists
  ansible.builtin.file:
    path: /etc/caddy/certs
    state: directory
    owner: caddy
    group: caddy
    mode: "0700"

- name: Copy Server Certificate to Caddy directory
  ansible.builtin.copy:
    src: /etc/ssl/certs/{{ inventory_hostname }}.ddmail.nebula.crt
    dest: /etc/caddy/certs/{{ inventory_hostname }}.ddmail.nebula.crt
    remote_src: True
    owner: caddy
    group: caddy
    mode: "0644"

- name: Copy Server Private Key to Caddy directory
  ansible.builtin.copy:
    src: /etc/ssl/private/{{ inventory_hostname }}.ddmail.nebula.key
    dest: /etc/caddy/certs/{{ inventory_hostname }}.ddmail.nebula.key
    remote_src: True
    owner: caddy
    group: caddy
    mode: "0600"

- name: Restart caddy service.
  ansible.builtin.service:
    name: caddy
    state: restarted
    enabled: true
