---
- name: Install prerequisite packages.
  ansible.builtin.apt:
    pkg:
      - gpg
      - apt-transport-https
      - curl
    state: latest

- name: Download Caddy stable GPG key.
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    dest: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    mode: "0644"
    force: true

- name: Add caddy apt repository with signed-by configuration.
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian trixie main"
    state: present
    filename: caddy
    update_cache: true

- name: Install latest version of caddy ignoring "install-recommends".
  ansible.builtin.apt:
    name: caddy
    state: latest
    install_recommends: false

- name: Create/edit caddy configuration file /etc/caddy/Caddyfile.
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Ensure Caddy certs directory exists
  ansible.builtin.file:
    path: /etc/caddy/certs
    state: directory
    owner: caddy
    group: caddy
    mode: "0700"

- name: Copy Server Certificate to Caddy directory
  ansible.builtin.copy:
    src: /etc/ssl/certs/{{ inventory_hostname }}.ddmail.nebula.crt
    dest: /etc/caddy/certs/{{ inventory_hostname }}.ddmail.nebula.crt
    remote_src: True
    owner: caddy
    group: caddy
    mode: "0644"

- name: Copy Server Private Key to Caddy directory
  ansible.builtin.copy:
    src: /etc/ssl/private/{{ inventory_hostname }}.ddmail.nebula.key
    dest: /etc/caddy/certs/{{ inventory_hostname }}.ddmail.nebula.key
    remote_src: True
    owner: caddy
    group: caddy
    mode: "0600"

- name: Restart caddy service.
  ansible.builtin.service:
    name: caddy
    state: restarted
    enabled: true
