---
- name: Install postfix packages.
  apt:
    pkg:
      - postfix
      - postfix-mysql
    state: latest

- name: Create/edit postfix configuration file main.cf
  template: src=main.cf.j2 dest=/etc/postfix/main.cf

- name: Create/edit postfix configuration file /etc/mailname
  template: src=mailname.j2 dest=/etc/mailname

- name: Create/edit postfix configuration file master.cf
  template: src=master.cf.j2 dest=/etc/postfix/master.cf

- name: Create/edit postfix configuration file mysql-virtual-domains.cf
  template: src=mysql-virtual-domains.cf.j2 dest=/etc/postfix/mysql-virtual-domains.cf

- name: Create/edit postfix configuration file mysql-virtual-emails.cf
  template: src=mysql-virtual-emails.cf.j2 dest=/etc/postfix/mysql-virtual-emails.cf

- name: Create/edit postfix configuration file mysql-virtual-alias.cf
  template: src=mysql-virtual-alias.cf.j2 dest=/etc/postfix/mysql-virtual-alias.cf

- name: Restar postfix Service
  service: name=postfix state=restarted enabled=yes
