---
- name: Install postfix packages.
  ansible.builtin.apt:
    pkg:
      - postfix
      - postfix-mysql
    state: latest

- name: Create/edit postfix configuration file main.cf
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf

- name: Create/edit postfix configuration file /etc/mailname
  ansible.builtin.template:
    src: mailname.j2
    dest: /etc/mailname

- name: Create/edit postfix configuration file master.cf
  ansible.builtin.template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf

- name: Create/edit postfix configuration file mysql-virtual-domains.cf
  ansible.builtin.template:
    src: mysql-virtual-domains.cf.j2
    dest: /etc/postfix/mysql-virtual-domains.cf

- name: Create/edit postfix configuration file mysql-virtual-emails.cf
  ansible.builtin.template:
    src: mysql-virtual-emails.cf.j2
    dest: /etc/postfix/mysql-virtual-emails.cf

- name: Create/edit postfix configuration file mysql-virtual-alias.cf
  ansible.builtin.template:
    src: mysql-virtual-alias.cf.j2
    dest: /etc/postfix/mysql-virtual-alias.cf

- name: Restart postfix service
  ansible.builtin.service:
    name: postfix
    state: restarted
    enabled: true
