---
- name: Install packages needed for ddmail openpgp encryptor
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
      - python3-venv
    state: latest

- name: Stat /opt/ddmail_openpgp_encryptor folder
  ansible.builtin.stat:
    path: /opt/ddmail_openpgp_encryptor
  register: ddmail_openpgp_encryptor

- name: Move /opt/ddmail_openpgp_encryptor folder
  ansible.builtin.command: mv /opt/ddmail_openpgp_encryptor /opt/ddmail_openpgp_encryptor_{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}
  when: ddmail_openpgp_encryptor.stat.exists

- name: Add the group "{{ ddmail_openpgp_encryptor_runas_group }}"
  ansible.builtin.group:
    name: "{{ ddmail_openpgp_encryptor_runas_group }}"
    state: present
  when: env == "prod"

- name: Add the user "{{ ddmail_openpgp_encryptor_runas_user }}"
  ansible.builtin.user:
    name: "{{ ddmail_openpgp_encryptor_runas_user }}"
    shell: /sbin/nologin
    create_home: false
    group: "{{ ddmail_openpgp_encryptor_runas_group }}"
    groups: "{{ ddmail_openpgp_keyhandler_runas_group }}"
    state: present
  when: env == "prod"

- name: Clone ddmail_openpgp_encryptor repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/drzobin/ddmail_openpgp_encryptor.git
    dest: /opt/ddmail_openpgp_encryptor
  when: env == "dev"

- name: Create /opt/ddmail_openpgp_encryptor if it does not exist
  ansible.builtin.file:
    path: /etc/ddmail_openpgp_encryptor
    state: directory
    mode: '0750'

- name: Create /opt/ddmail_openpgp_encryptor/config if it does not exist
  ansible.builtin.file:
    path: /etc/ddmail_openpgp_encryptor/config
    state: directory
    mode: '0750'

- name: Create ddmail_openpgp_encryptor python env.
  ansible.builtin.command: python3 -m venv /opt/ddmail_openpgp_encryptor/venv

- name: Install ddmail_openpgp_encryptor and its dev requirenments with pip.
  ansible.builtin.pip:
    name: .[dev]
    path: /opt/ddmail_openpgp_encryptor
    extra_args: -e
    virtualenv_python: python3
    virtualenv: /opt/ddmail_openpgp_encryptor/venv
  when: env == "dev"

- name: Install ddmail_openpgp_encryptor and its requirenments with pip.
  ansible.builtin.pip:
    name: ddmail-openpgp-encryptor
    virtualenv_python: python3
    virtualenv: /opt/ddmail_openpgp_encryptor/venv
  when: env == "prod"

- name: Set user and group ownership of /opt/ddmail_openpgp_encryptor
  ansible.builtin.file:
    state: directory
    recurse: true
    owner: "{{ ddmail_openpgp_encryptor_venv_user_owner }}"
    group: "{{ ddmail_openpgp_encryptor_venv_group_owner }}"
    path: /opt/ddmail_openpgp_encryptor

- name: Set git remote for ddmail_openpgp_encryptor
  ansible.builtin.shell: cd /opt/ddmail_openpgp_encryptor; git remote set-url origin git@github.com:drzobin/ddmail_openpgp_encryptor.git
  become: true
  become_method: su
  become_user: "{{ ddmail_openpgp_encryptor_runas_user }}"
  when: env == "dev"

- name: Create/edit ddmail_openpgp_encryptor config file /opt/ddmail_openpgp_encryptor/config/config.ini
  ansible.builtin.template:
    src: config.ini.j2
    dest: /opt/ddmail_openpgp_encryptor/openpgp_encryptor/config/config.ini
    owner: '{{ ddmail_openpgp_encryptor_runas_user }}'
    group: '{{ ddmail_openpgp_encryptor_runas_group }}'
    mode: "u=rw,g=r,o="

- name: Add logdir for ddmail_openpgp_encryptor.
  ansible.builtin.file:
    path: /var/log/ddmail_openpgp_encryptor.log
    state: touch
    owner: '{{ ddmail_openpgp_encryptor_runas_user }}'
    group: '{{ ddmail_openpgp_encryptor_runas_group }}'
    mode: u=rw,g=r,o=

- name: Create/edit ddmail_openpgp_encryptor service configuration file /etc/systemd/system/ddmail_openpgp_encryptor.service
  ansible.builtin.template:
    src: systemd_service.j2
    dest: /etc/systemd/system/ddmail_openpgp_encryptor.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  when: env == "prod"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: env == "prod"

- name: Restart ddmail_openpgp_encryptor service
  ansible.builtin.service:
    name: ddmail_openpgp_encryptor
    state: restarted
    enabled: true
  when: env == "prod"

- name: Kill development server in screen.
  ansible.builtin.command: screen -X -S ddmail_openpgp_encryptor kill
  become: true
  become_method: su
  become_user: "{{ ddmail_openpgp_encryptor_runas_user }}"
  ignore_errors: true
  when: env == "dev"

- name: Start development server in screen.
  ansible.builtin.command: screen -S ddmail_opengpg_encryptor -d -m bash -c "sleep 5; source /opt/ddmail_openpgp_encryptor/venv/bin/activate; cd /opt/ddmail_openpgp_encryptor; export MODE=DEVELOPMENT; openpgp_encryptor --config-file config/config.ini"
  become: true
  become_method: su
  become_user: "{{ ddmail_openpgp_encryptor_runas_user }}"
  when: env == "dev"
