---
- name: Install packages need to add mariadb repo.
  apt:
    pkg:
      - python3-pip
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
      - python3-venv
      - default-libmysqlclient-dev
      - apache2
    state: latest

- name: Enable apache2 mod proxy
  ansible.builtin.command: /usr/sbin/a2enmod proxy

- name: Enable apache2 mod proxy_http
  ansible.builtin.command: /usr/sbin/a2enmod proxy_http

- name: Create/edit apache2 config file /etc/apache2/sites-enabled/000-default.conf 
  template: src=000-default.conf.j2 dest=/etc/apache2/sites-enabled/000-default.conf

- name: Restar apache2 service
  service: name=apache2 state=restarted enabled=yes

- name: Create dmail python env.
  command: python3 -m venv /opt/www_ddmail_se_env

- name: Install Flask with pip.
  pip:
    name: flask
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/www_ddmail_se_env

- name: Install Flask-SQLAlchemy with pip.
  pip:
    name: Flask-SQLAlchemy
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/www_ddmail_se_env

- name: Install argon2_cffi with pip.
  pip:
    name: argon2_cffi
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/www_ddmail_se_env

- name: Install Flask-Session with pip.
  pip:
    name: Flask-Session
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/www_ddmail_se_env

- name: Install Flask-WTF with pip.
  pip:
    name: Flask-WTF
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/www_ddmail_se_env

- name: Install mysqlclient with pip.
  pip:
    name: mysqlclient
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/www_ddmail_se_env

- name: Install pytest with pip.
  pip:
    name: pytest
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/www_ddmail_se_env

- name: Install coverage with pip.
  pip:
    name: coverage
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/www_ddmail_se_env

- name: Install gunicorn with pip.
  pip:
    name: gunicorn
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/www_ddmail_se_env

- name: Create/edit ddmail gunicorne service configuration file /etc/systemd/system/ddmail_gunicorn.service 
  template: src=ddmail_gunicorn.service.j2 dest=/etc/systemd/system/ddmail_gunicorn.service

- name: Restar ddmail_gunicorn Service
  service: name=ddmail_gunicorn state=restarted enabled=yes
