---
- name: Install packages need to add mariadb repo.
  apt:
    pkg:
    - software-properties-common 
    - dirmngr 
    - apt-transport-https

- name: Get mariadb repo key.
  command: /usr/bin/apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'

- name: Add mariadb repo.
  command: /usr/bin/add-apt-repository 'deb [trusted=yes arch=amd64] https://ftp.icm.edu.pl/pub/unix/database/mariadb/repo/10.5/debian buster main'

- name: Run apt-get update.
  command: /usr/bin/apt-get update

- name: Install mariadb server.
  apt:
    name: mariadb-server
    update_cache: yes
    state: latest
