---
- name: Install packages needed for certbot to get letsencrypt ssl/tls cert
  ansible.builtin.apt:
    pkg:
      - certbot
      - python3-certbot-apache
      - apache2
    state: latest

- name: Stat cerbot registration lockfile
  ansible.builtin.stat:
    path: /etc/letsencrypt/.registered
  register: certbot_reg_lockfile

- name: Stop apache2 service for certbot registration
  ansible.builtin.service:
    name: apache2
    state: stopped
    enabled: true
  when: not certbot_reg_lockfile.stat.exists

- name: Register certbot
  ansible.builtin.command: certbot -n register --agree-tos --email {{ vault_certbot_reg_email }}
  when: not certbot_reg_lockfile.stat.exists

- name: Create certbot registration lockfile
  ansible.builtin.command: touch /etc/letsencrypt/.registered
  when: not certbot_reg_lockfile.stat.exists

- name: Get ssl/tls certificates
  ansible.builtin.include_tasks: get_cert.yml
  loop: "{{ certbot_certs }}"
  loop_control:
    loop_var: cert

- name: Restart apache2 service
  ansible.builtin.service:
    name: apache2
    state: restarted
    enabled: true
