---
- name: Install dep packages.
  apt:
    name: python3-pymysql
    update_cache: true
    state: latest

- name: Create mail system database
  mysql_db:
    name: "{{ mail_db_name }}"
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock
    state: present

- name: Create mail database user user_r with read access
  mysql_user:
    name: "{{ mail_db_user_r }}"
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock
    password: "{{ mail_db_user_r_password }}"
    priv: "{{ mail_db_name }}.*:SELECT"
    host: localhost
    state: present

- name: Create mail database user user_rw with read and write access
  mysql_user:
    name: "{{ mail_db_user_rw }}"
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock
    password: "{{ mail_db_user_rw_password }}"
    priv: "{{ mail_db_name }}.*:ALL"
    host: localhost
    state: present

- name: Create MariaDB create tables sql file
  copy:
    src: create_tables.sql
    dest: /root/create_tables.sql

- name: Create tables for mail db using create tables sql file
  mysql_db:
    name: "{{ mail_db_name }}"
    login_user: "{{ mail_db_user_rw }}"
    login_password: "{{ mail_db_user_rw_password }}"
    state: import
    target: /root/create_tables.sql
