---
- name: Install nftables.
  ansible.builtin.apt:
    pkg:
      - nftables
    state: latest

- name: Create/edit nftables configuration file /etc/nftables.conf
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf

- name: Restart nftables service
  ansible.builtin.service:
    name: nftables
    state: restarted
    enabled: true
