---
- name: Install nftables.
  apt:
    pkg:
      - nftables
    state: latest

- name: Create/edit nftables configuration file /etc/nftables.conf
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf

- name: Restar nftables service
  service:
    name: nftables
    state: restarted
    enabled: true
