---
- name: Install packages needed for web application ddmail
  ansible.builtin.apt:
    pkg:
      - python3
      - tar
      - gpg
      - secure-delete
    state: latest

- name: Add gpg public key for root used during encryption of backups
  ansible.builtin.copy: 
    content: "{{ ddmail_backup_taker_pubkey }}"
    dest: /root/ddmail_backups_pubkey.txt
    owner: root
    group: root
    mode: "u=rw,g=,o="

- name: Import gpg pubkey used for encrypting backups.
  ansible.builtin.command: gpg --import /root/ddmail_backups_pubkey.txt

- name: Stat /root/ddmail_backup_taker folder
  ansible.builtin.stat:
    path: /root/ddmail_backup_taker
  register: ddmail_backup_taker

- name: Move /root/ddmail_backup_taker folder
  ansible.builtin.command: mv /root/ddmail_backup_taker /root/ddmail_backup_taker_{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}
  when: ddmail_backup_taker.stat.exists

- name: Create /root/ddmail_backup_taker if it does not exist
  ansible.builtin.file:
    path: /root/ddmail_backup_taker
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o="

- name: Create /root/ddmail_backup_taker/config if it does not exist
  ansible.builtin.file:
    path: /root/ddmail_backup_taker/config
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o="

- name: Clone ddmail_backup_taker repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/drzobin/ddmail_backup_taker.git
    dest: /root/ddmail_backup_taker/ddmail_backup_taker
  when: env == "dev"

- name: Create ddmail_backup_taker python venv.
  ansible.builtin.command: python3 -m venv /root/ddmail_backup_taker/venv

- name: Install ddmail_backup_taker and requirenments for production with pip.
  ansible.builtin.pip:
    name: ddmail-backup-taker
    state: latest
    virtualenv_python: python3
    virtualenv: /root/ddmail_backup_taker/venv
  when: env == "prod"

- name: Install ddmail_backup_taker and requirenments for development with pip.
  ansible.builtin.pip:
    name: .[dev]
    chdir: /root/ddmail_backup_taker/ddmail_backup_taker
    state: latest
    virtualenv_python: python3
    virtualenv: /root/ddmail_backup_taker/venv
  when: env == "dev"

- name: Set user and group ownership of /root/ddmail_backup_taker
  ansible.builtin.file:
    state: directory
    recurse: true
    owner: root
    group: root
    path: /root/ddmail_backup_taker

- name: Set git remote for ddmail_backup_taker
  ansible.builtin.shell: cd /root/ddmail_backup_taker/ddmail_backup_taker; git remote set-url origin git@github.com:drzobin/ddmail_backup_taker.git
  when: env == "dev"

- name: Create/edit ddmail_backup config file /root/ddmail_backup_taker/config/config.toml
  ansible.builtin.template:
    src: config.toml.j2
    dest: /root/ddmail_backup_taker/config/config.toml
    owner: root
    group: root
    mode: "u=rw,g=,o="

- name: Add backup folder.
  ansible.builtin.file:
    path: /root/backups
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=,o="

- name: Add backup tmp folder.
  ansible.builtin.file:
    path: /root/backups/tmp
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=,o="

- name: Ensure ddmail_backup_taker runs at 5 every day.
  ansible.builtin.cron:
    name: "Take backups"
    minute: "0"
    hour: "5"
    job: "/root/ddmail_backup_taker/venv/bin/ddmail_backup_taker --config-file /root/ddmail_backup_taker/config/config.toml > /dev/null 2>&1"
