---
- name: Install packages needed for web application ddmail
  ansible.builtin.apt:
    pkg:
      - python3
      - tar
      - gpg
    state: latest

- name: Stat /root/ddmail_backup_taker folder
  ansible.builtin.stat:
    path: /root/ddmail_backup_taker
  register: ddmail_backup_taker

- name: Move /root/ddmail_backup_taker folder
  ansible.builtin.command: mv /root/ddmail_backup_taker /root/ddmail_backup_taker_{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}
  when: ddmail_backup_taker.stat.exists

- name: Clone ddmail_backup_taker repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/drzobin/ddmail_backup_taker.git
    dest: /root/ddmail_backup_taker

- name: Create ddmail_backup_taker python env.
  ansible.builtin.command: python3 -m venv /root/ddmail_backup_taker/backup_taker/venv

- name: Install requirenments with pip.
  ansible.builtin.pip:
    requirements: /root/ddmail_backup_taker/backup_taker/requirements.txt
    state: latest
    virtualenv_python: python3
    virtualenv: /root/ddmail_backup_taker/backup_taker/venv

- name: Set user and group ownership of /root/ddmail_backup_taker
  ansible.builtin.file:
    state: directory
    recurse: true
    owner: root
    group: root
    path: /root/ddmail_backup_taker

- name: Set git remote for ddmail_backup_taker
  ansible.builtin.shell: cd /root/ddmail_backup_taker; git remote set-url origin git@github.com:drzobin/ddmail_backup_taker.git
  when: env == "dev"

- name: Create/edit ddmail_backup config file /root/ddmail_backup_taker/backup_taker/config.ini
  ansible.builtin.template:
    src: config.ini.j2
    dest: /root/ddmail_backup_taker/backup_taker/config.ini
    owner: root
    group: root
    mode: "u=rw,g=,o="

- name: Add backup folder.
  ansible.builtin.file:
    path: /root/backups
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=,o="

- name: Add backup tmp folder.
  ansible.builtin.file:
    path: /root/backups/tmp
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=,o="

- name: Ensure ddmail_backup_taker runs at 5 every day.
  ansible.builtin.cron:
    name: "Take backups"
    minute: "0"
    hour: "5"
    job: "/root/ddmail_backup_taker/backup_taker/venv/bin/python3 /root/ddmail_backup_taker/backup_taker/backup_taker/take_backup.py --config-file /root/ddmail_backup_taker/backup_taker/config.ini > /dev/null 2>&1"
