---
- name: Install dep package.
  ansible.builtin.apt:
    pkg:
      - gpg
      - apt-transport-https
    state: latest

- name: Add rspamd apt signing key.
  ansible.builtin.apt_key:
    url: https://rspamd.com/apt-stable/gpg.key
    state: present

- name: Add rspamd apt repository.
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://rspamd.com/apt-stable/ bookworm main"
    state: present
    filename: rspamd
    update_cache: true

- name: Add rspamdi src apt repository.
  ansible.builtin.apt_repository:
    repo: "deb-src [arch=amd64] https://rspamd.com/apt-stable/ bookworm main"
    state: present
    filename: rspamd
    update_cache: true

- name: Run "apt-get update".
  ansible.builtin.apt:
    update_cache: true

- name: Install latest version of rspamd ignoring "install-recommends".
  ansible.builtin.apt:
    name: rspamd
    state: latest
    install_recommends: false
    update_cache: true

- name: Create/edit rspamd configuration file /etc/rspamd/local.d/worker-normal.inc.
  ansible.builtin.template:
    src: etc_rspamd_local.d_worker-normal.inc.j2
    dest: /etc/rspamd/local.d/worker-normal.inc
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Create/edit rspamd configuration file /etc/rspamd/local.d/worker-proxy.inc.
  ansible.builtin.template:
    src: etc_rspamd_local.d_worker-proxy.inc.j2
    dest: /etc/rspamd/local.d/worker-proxy.inc
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Create/edit rspamd configuration file /etc/rspamd/local.d/worker-controller.inc.
  ansible.builtin.template:
    src: etc_rspamd_local.d_worker-controller.inc.j2
    dest: /etc/rspamd/local.d/worker-controller.inc
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Create/edit rspamd configuration file /etc/rspamd/local.d/milter_headers.conf
  ansible.builtin.template:
    src: etc_rspamd_local.d_milter_headers.conf.j2
    dest: /etc/rspamd/local.d/milter_headers.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Create/edit rspamd configuration file /etc/rspamd/local.d/classifier-bayes.conf
  ansible.builtin.template:
    src: etc_rspamd_local.d_classifier-bayes.conf.j2
    dest: /etc/rspamd/local.d/classifier-bayes.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Create folder to store dkim key in.
  ansible.builtin.file:
    path: /var/lib/rspamd/dkim/
    state: directory
    owner: _rspamd
    group: _rspamd
    mode: "u=rwx,g=rwxs,o="

- name: Stat dkim key file /var/lib/rspamd/dkim/mail.key
  ansible.builtin.stat:
    path: /var/lib/rspamd/dkim/mail.key
  register: dkim_key

- name: Create dkim cert.
  ansible.builtin.shell: >
    /usr/bin/rspamadm dkim_keygen -b 2048 -s mail -k /var/lib/rspamd/dkim/mail.key |
    /usr/bin/tee -a /var/lib/rspamd/dkim/mail.pub
  when: not dkim_key.stat.exists

- name: Set premission on dkim private key.
  ansible.builtin.file:
    path: /var/lib/rspamd/dkim/mail.key
    owner: root
    group: _rspamd
    mode: "u=rwx,g=r,o="

- name: Set premission on dkim pub key.
  ansible.builtin.file:
    path: /var/lib/rspamd/dkim/mail.pub
    owner: root
    group: _rspamd
    mode: "u=rwx,g=r,o="

- name: Create/edit rspamd configuration file for dkim /etc/rspamd/local.d/dkim_signing.conf.
  ansible.builtin.template:
    src: etc_rspamd_local.d_dkim_signing.conf.j2
    dest: /etc/rspamd/local.d/dkim_signing.conf

- name: Create/edit rspamd configuration file for arc /etc/rspamd/local.d/arc.conf.
  ansible.builtin.template:
    src: etc_rspamd_local.d_dkim_signing.conf.j2
    dest: /etc/rspamd/local.d/arc.conf

- name: Create/edit rspamd configuration file for antivirus clamav /etc/rspamd/local.d/antivirus.conf.
  ansible.builtin.template:
    src: antivirus.conf.j2
    dest: /etc/rspamd/local.d/antivirus.conf
    owner: root
    group: root
    mode: "u=rwx,g=r,o=r"

- name: Create/edit rspamd configuration file for phishing roles/rspamd/templates/phishing.conf.
  ansible.builtin.template:
    src: phishing.conf.j2
    dest: /etc/rspamd/local.d/phishing.conf
    owner: root
    group: root
    mode: "u=rwx,g=r,o=r"

- name: Create/edit rspamd configuration file for antivirus /etc/rspamd/local.d/antivirus.conf.
  ansible.builtin.template:
    src: antivirus.conf.j2
    dest: /etc/rspamd/local.d/antivirus.conf
    owner: root
    group: root
    mode: "u=rwx,g=r,o=r"

- name: Create/edit rspamd configuration file for force actions /etc/rspamd/local.d/force_actions.conf.
  ansible.builtin.template:
    src: force_actions.conf.j2
    dest: /etc/rspamd/local.d/force_actions.conf
    owner: root
    group: root
    mode: "u=rwx,g=r,o=r"

- name: Create/edit rspamd configuration file for systemd /lib/systemd/system/rspamd.service.
  ansible.builtin.template:
    src: rspamd.service.j2
    dest: /lib/systemd/system/rspamd.service
    owner: root
    group: root
    mode: "u=rwx,g=r,o=r"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart rspamd service
  ansible.builtin.service:
    name: rspamd
    state: restarted
    enabled: true
