---
- name: Install openssl packages.
  ansible.builtin.apt:
    pkg:
      - openssl
    state: latest

- name: Add dir for self signed certs.
  ansible.builtin.file:
    path: "{{ self_signed_certs_folder }}"
    state: directory
    recurse: yes
    owner: 'root'
    group: 'root'
    mode: "u=rwx,g=rx,o=rx"

- name: Create self signed cert for dev.ddmail.local
  ansible.builtin.command: openssl req -x509 -newkey rsa:4096 -keyout "{{ self_signed_certs_key }}" -out "{{ self_signed_certs_cert }}" -sha256 -days 365 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN={{ hostvars[inventory_hostname]['fqdn'] }}"
