---
- name: Install openssl packages.
  ansible.builtin.apt:
    pkg:
      - openssl
    state: latest

- name: Add dir for self signed certs.
  ansible.builtin.file:
    path: "{{ self_signed_certs_folder }}"
    state: directory
    owner: 'root'
    group: 'root'
    mode: "u=rwx,g=rx,o=rx"

- name: Add dir for self signed cert for mail.ddmail.se.
  ansible.builtin.file:
    path: "{{ self_signed_certs_folder_mail_ddmail_se }}"
    state: directory
    owner: 'root'
    group: 'root'
    mode: "u=rwx,g=rx,o=rx"

- name: Create self signed cert for mail.ddmail.se
  ansible.builtin.command: openssl req -x509 -newkey rsa:4096 -keyout "{{ self_signed_certs_privkey_mail_ddmail_se }}" -out "{{ self_signed_certs_cert_mail_ddmail_se }}" -sha256 -days 3650 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=mail.ddmail.se"
