---
- name: Install openssl packages.
  ansible.builtin.apt:
    pkg:
      - openssl
    state: latest

- name: Add dir for self signed certs.
  ansible.builtin.file:
    path: "{{ self_signed_certs_folder }}"
    state: directory
    owner: 'root'
    group: 'root'
    mode: "u=rwx,g=rx,o=rx"

- name: Add dir for self signed cert for dev.ddmail.local
  ansible.builtin.file:
    path: "{{ self_signed_certs_folder_dev_ddmail_local }}"
    state: directory
    owner: 'root'
    group: 'root'
    mode: "u=rwx,g=rx,o=rx"

- name: Create self signed cert for dev.ddmail.local
  ansible.builtin.command: openssl req -x509 -newkey rsa:4096 -keyout "{{ self_signed_certs_privkey_dev_ddmail_local }}" -out "{{ self_signed_certs_cert_dev_ddmail_local }}" -sha256 -days 3650 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=dev.ddmail.local"
