---
- name: Install general package.
  apt:
    pkg:
      - vim
      - telnet
      - net-tools
      - dnsutils
      - mlocate
      - git
      - apt-transport-https
      - wget
    state: latest
