---
- name: Install packages needed for ddmail backup receiver
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
      - python3-venv
    state: latest

- name: Install screen in dev
  ansible.builtin.apt:
    pkg:
      - screen
    state: latest
  when: env == "dev"

- name: Stat /opt/ddmail_backup_receiver folder
  ansible.builtin.stat:
    path: /opt/ddmail_backup_receiver
  register: ddmail_backup_receiver

- name: Move /opt/ddmail_backup_receiver folder
  ansible.builtin.command: mv /opt/ddmail_backup_receiver /opt/ddmail_backup_receiver_{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}
  when: ddmail_backup_receiver.stat.exists

- name: Create /opt/ddmail_backup_receiver if it does not exist
  ansible.builtin.file:
    path: /opt/ddmail_backup_receiver
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"

- name: Create ddmail_backup_receiver python env.
  ansible.builtin.command: python3 -m venv /opt/ddmail_backup_receiver/venv

- name: Add the group "{{ ddmail_backup_receiver_runas_group }}"
  ansible.builtin.group:
    name: "{{ ddmail_backup_receiver_runas_group }}"
    state: present
  when: env == "prod"

- name: Add the user "{{ ddmail_backup_receiver_runas_user }}"
  ansible.builtin.user:
    name: "{{ ddmail_backup_receiver_runas_user }}"
    shell: /sbin/nologin
    create_home: false
    group: "{{ ddmail_backup_receiver_runas_group }}"
    state: present
  when: env == "prod"

- name: Clone ddmail_backup_receiver repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/drzobin/ddmail_backup_receiver.git
    dest: /opt/ddmail_backup_receiver/ddmail_backup_receiver
  when: env == "dev"

- name: Install ddmail_backup_receiver and requirenments with pip.
  ansible.builtin.pip:
    name: ddmail-backup-receiver
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/ddmail_backup_receiver/venv
  when: env == "prod"

- name: Install ddmail_backup_receiver and requirenments for development with pip.
  ansible.builtin.pip:
    name: .[dev]
    chdir: /opt/ddmail_backup_receiver/ddmail_backup_receiver
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/ddmail_backup_receiver/venv
  when: env == "dev"

- name: Set user and group ownership of /opt/ddmail_backup_receiver_venv
  ansible.builtin.file:
    state: directory
    recurse: true
    owner: "{{ ddmail_backup_receiver_user_owner }}"
    group: "{{ ddmail_backup_receiver_group_owner }}"
    path: /opt/ddmail_backup_receiver

- name: Set git remote for ddmail_backup_receiver
  ansible.builtin.shell: cd /opt/ddmail_backup_receiver/ddmail_backup_receiver; git remote set-url origin git@github.com:drzobin/ddmail_backup_receiver.git
  become: true
  become_method: su
  become_user: "{{ ddmail_backup_receiver_runas_user }}"
  when: env == "dev"

- name: Create /opt/ddmail_backup_receiver/config if it does not exist
  ansible.builtin.file:
    path: /opt/ddmail_backup_receiver/config
    state: directory
    owner: "{{ ddmail_backup_receiver_user_owner }}"
    group: "{{ ddmail_backup_receiver_group_owner }}"
    mode: "u=rwx,g=rx,o=rx"

- name: Create/edit ddmail_backup_receiver config file /opt/ddmail_backup_receiver/config/config.toml
  ansible.builtin.template:
    src: config.toml.j2
    dest: /opt/ddmail_backup_receiver/config/config.toml
    owner: '{{ ddmail_backup_receiver_runas_user }}'
    group: '{{ ddmail_backup_receiver_runas_group }}'
    mode: "u=rw,g=r,o="

- name: Create/edit ddmail_backup_receiver gunicorne service configuration file /etc/systemd/system/ddmail_backup_receiver.service
  ansible.builtin.template:
    src: systemd_service.j2
    dest: /etc/systemd/system/ddmail_backup_receiver.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  when: env == "prod"

- name: Add logdir for gunicorn.
  ansible.builtin.file:
    path: /var/log/gunicorn
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  when: env == "prod"

- name: Add logfile for ddmail_backup_receiver gunicorn.
  ansible.builtin.file:
    path: /var/log/gunicorn/ddmail_backup_receiver.log
    state: touch
    owner: '{{ ddmail_backup_receiver_runas_user }}'
    group: '{{ ddmail_backup_receiver_runas_group }}'
    mode: u=rw,g=r,o=
  when: env == "prod"

- name: Add logfile for ddmail_backup_receiver.
  ansible.builtin.file:
    path: /var/log/ddmail_backup_receiver.log
    state: touch
    owner: '{{ ddmail_backup_receiver_runas_user }}'
    group: '{{ ddmail_backup_receiver_runas_group }}'
    mode: u=rw,g=r,o=
  when: env == "prod"

- name: Add logfile for ddmail_backup_receiver.
  ansible.builtin.file:
    path: /var/log/ddmail_backup_receiver.log
    state: touch
    owner: '{{ ddmail_backup_receiver_runas_user }}'
    group: '{{ ddmail_backup_receiver_runas_user }}'
    mode: u=rw,g=r,o=
  when: env == "dev"

- name: Add backup dir
  ansible.builtin.file:
    path: /opt/ddmail_backup_receiver_venv/ddmail_backup_receiver/backup_receiver/backups/
    state: directory
    owner: '{{ ddmail_backup_receiver_runas_user }}'
    group: '{{ ddmail_backup_receiver_runas_user }}'
    mode: "u=rwx,g=rx,o="
  when: env == "dev"

- name: Add backup dir
  ansible.builtin.file:
    path: /opt/ddmail_backup_receiver_venv/backup_receiver/backups/
    state: directory
    owner: '{{ ddmail_backup_receiver_runas_user }}'
    group: '{{ ddmail_backup_receiver_runas_user }}'
    mode: "u=rwx,g=rx,o="
  when: env == "prod"

- name: Kill development server in screen.
  ansible.builtin.command: screen -X -S ddmail_backup_receiver quit
  become: true
  become_method: su
  become_user: "{{ ddmail_backup_receiver_runas_user }}"
  ignore_errors: true
  when: env == "dev"

- name: Wipe dead screen.
  ansible.builtin.command: screen -wipe
  become: true
  become_method: su
  become_user: "{{ ddmail_backup_receiver_runas_user }}"
  when: env == "dev"

- name: Create/edit ddmail_backup_receiver startup script for development
  ansible.builtin.template:
    src: run_dev.sh.j2
    dest: /opt/ddmail_backup_receiver/run_dev.sh
    owner: "{{ ddmail_backup_receiver_runas_user }}"
    group: "{{ ddmail_backup_receiver_runas_group }}"
    mode: "u=rwx,g=r,o=r"
  when: env == "dev"

- name: Start development server in screen.
  ansible.builtin.command: screen -S ddmail_backup_receiver -d -m bash -c "sleep 5; /opt/ddmail_backup_receiver/run_dev.sh; /bin/bash"
  become: true
  become_method: su
  become_user: "{{ ddmail_backup_receiver_runas_user }}"
  when: env == "dev"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: env == "prod"

- name: Restart ddmail_backup_receiver gunicorn service
  ansible.builtin.service:
    name: ddmail_backup_receiver
    state: restarted
    enabled: true
  when: env == "prod"
