---
- name: Install packages needed for web application ddmail
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
      - python3-venv
      - gpg
    state: latest

- name: Install screen in dev
  ansible.builtin.apt:
    pkg:
      - screen
    state: latest
  when: env == "dev"

- name: Stat /opt/ddmail_openpgp_keyhandler folder
  ansible.builtin.stat:
    path: /opt/ddmail_openpgp_keyhandler
  register: ddmail_openpgp_keyhandler

- name: Move /opt/ddmail_openpgp_keyhandler folder
  ansible.builtin.command: mv /opt/ddmail_openpgp_keyhandler /opt/ddmail_openpgp_keyhandler_{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}
  when: ddmail_openpgp_keyhandler.stat.exists

- name: Create /opt/ddmail_openpgp_keyhandler if it does not exist
  ansible.builtin.file:
    path: /opt/ddmail_openpgp_keyhandler
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  when: env == "prod"

- name: Create /opt/ddmail_openpgp_keyhandler if it does not exist
  ansible.builtin.file:
    path: /opt/ddmail_openpgp_keyhandler
    state: directory
    owner: '{{ ddmail_openpgp_keyhandler_runas_user }}'
    group: '{{ ddmail_openpgp_keyhandler_runas_group }}'
    mode: "u=rwx,g=rx,o=rx"
  when: env == "dev"

- name: Clone ddmail_openpgp_keyhandler repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/drzobin/ddmail_openpgp_keyhandler.git
    dest: /opt/ddmail_openpgp_keyhandler/ddmail_openpgp_keyhandler
  when: env == "dev"

- name: Create ddmail_openpgp_keyhandler python env.
  ansible.builtin.command: python3 -m venv /opt/ddmail_openpgp_keyhandler/venv

- name: Add the group "{{ ddmail_openpgp_keyhandler_runas_group }}"
  ansible.builtin.group:
    name: "{{ ddmail_openpgp_keyhandler_runas_group }}"
    state: present
  when: env == "prod"

- name: Add the user "{{ ddmail_openpgp_keyhandler_runas_user }}"
  ansible.builtin.user:
    name: "{{ ddmail_openpgp_keyhandler_runas_user }}"
    shell: /sbin/nologin
    create_home: false
    group: "{{ ddmail_openpgp_keyhandler_runas_group }}"
    state: present
  when: env == "prod"

- name: Install ddmail_openpgp_keyhandler and requirenments with pip.
  ansible.builtin.pip:
    name: ddmail-openpgp-keyhandler
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/ddmail_openpgp_keyhandler/venv
  when: env == "prod"

- name: Install requirenments for development with pip.
  ansible.builtin.pip:
    name: .[dev]
    chdir: /opt/ddmail_openpgp_keyhandler/ddmail_openpgp_keyhandler
    state: latest
    virtualenv_python: python3
    virtualenv: /opt/ddmail_openpgp_keyhandler/venv
  when: env == "dev"

- name: Set user and group ownership of /opt/ddmail_openpgp_keyhandler
  ansible.builtin.file:
    state: directory
    recurse: true
    owner: "{{ ddmail_openpgp_keyhandler_user_owner }}"
    group: "{{ ddmail_openpgp_keyhandler_group_owner }}"
    path: /opt/ddmail_openpgp_keyhandler

- name: Set git remote for ddmail_openpgp_keyhandler
  ansible.builtin.shell: cd /opt/ddmail_openpgp_keyhandler/ddmail_openpgp_keyhandler; git remote set-url origin git@github.com:drzobin/ddmail_openpgp_keyhandler.git
  become: true
  become_method: su
  become_user: "{{ ddmail_openpgp_keyhandler_runas_user }}"
  when: env == "dev"

- name: Create /opt/ddmail_openpgp_keyhandler/config if it does not exist
  ansible.builtin.file:
    path: /opt/ddmail_openpgp_keyhandler/config
    state: directory
    owner: '{{ ddmail_openpgp_keyhandler_runas_user }}'
    group: '{{ ddmail_openpgp_keyhandler_runas_group }}'
    mode: "u=rwx,g=rx,o="

- name: Create/edit ddmail_openpgp_keyhandler config file /opt/ddmail_openpgp_keyhandler/config/config.toml
  ansible.builtin.template:
    src: config.toml.j2
    dest: /opt/ddmail_openpgp_keyhandler/config/config.toml
    owner: '{{ ddmail_openpgp_keyhandler_runas_user }}'
    group: '{{ ddmail_openpgp_keyhandler_runas_group }}'
    mode: "u=rw,g=r,o="

- name: Create/edit ddmail_openpgp_keyhandler gunicorne service configuration file /etc/systemd/system/ddmail_openpgp_keyhandler.service
  ansible.builtin.template:
    src: systemd_service.j2
    dest: /etc/systemd/system/ddmail_openpgp_keyhandler.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  when: env == "prod"

- name: Add logdir for gunicorn.
  ansible.builtin.file:
    path: /var/log/gunicorn
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  when: env == "prod"

- name: Add logfile for ddmail_openpgp_keyhandler gunicorn.
  ansible.builtin.file:
    path: /var/log/gunicorn/ddmail_openpgp_keyhandler.log
    state: touch
    owner: '{{ ddmail_openpgp_keyhandler_runas_user }}'
    group: '{{ ddmail_openpgp_keyhandler_runas_group }}'
    mode: u=rw,g=r,o=
  when: env == "prod"

- name: Add logfile for ddmail_openpgp_keyhandler.
  ansible.builtin.file:
    path: /var/log/ddmail_openpgp_keyhandler.log
    state: touch
    owner: '{{ ddmail_openpgp_keyhandler_runas_user }}'
    group: '{{ ddmail_openpgp_keyhandler_runas_group }}'
    mode: u=rw,g=r,o=

- name: Add keyring/gnupg home folder for prod.
  ansible.builtin.file:
    path: "{{ ddmail_openpgp_keyhandler_prod_gnupg_home }}"
    state: directory
    owner: "{{ ddmail_openpgp_keyhandler_runas_user }}"
    group: "{{ ddmail_openpgp_keyhandler_runas_group }}"
    mode: "u=rwx,g=rx,o="
  when: env == "prod"

- name: Add keyring/gnupg home folder for dev.
  ansible.builtin.file:
    path: "{{ ddmail_openpgp_keyhandler_dev_gnupg_home }}"
    state: directory
    owner: "{{ ddmail_openpgp_keyhandler_runas_user }}"
    group: "{{ ddmail_openpgp_keyhandler_runas_group }}"
    mode: "u=rwx,g=rx,o="
  when: env == "dev"

- name: Add keyring/gnupg home folder for test.
  ansible.builtin.file:
    path: "{{ ddmail_openpgp_keyhandler_test_gnupg_home }}"
    state: directory
    owner: "{{ ddmail_openpgp_keyhandler_runas_user }}"
    group: "{{ ddmail_openpgp_keyhandler_runas_group }}"
    mode: "u=rwx,g=rx,o="

- name: Kill development server in screen.
  ansible.builtin.command: screen -X -S ddmail_openpgp_keyhandler quit
  become: true
  become_method: su
  become_user: "{{ ddmail_openpgp_keyhandler_runas_user }}"
  ignore_errors: true
  when: env == "dev"

- name: Wipe dead screen.
  ansible.builtin.command: screen -wipe
  become: true
  become_method: su
  become_user: "{{ ddmail_openpgp_keyhandler_runas_user }}"
  when: env == "dev"

- name: Create/edit ddmail_openpgp_keyhandler startup script for development
  ansible.builtin.template:
    src: run_dev.sh.j2
    dest: /opt/ddmail_openpgp_keyhandler/run_dev.sh
    owner: "{{ ddmail_openpgp_keyhandler_runas_user }}"
    group: "{{ ddmail_openpgp_keyhandler_runas_group }}"
    mode: "u=rwx,g=r,o=r"
  when: env == "dev"

- name: Start development server in screen.
  ansible.builtin.command: screen -S ddmail_openpgp_keyhandler -d -m bash -c "sleep 5; source /opt/ddmail_openpgp_keyhandler/run_dev.sh; /bin/bash"
  become: true
  become_method: su
  become_user: "{{ ddmail_openpgp_keyhandler_runas_user }}"
  when: env == "dev"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: env == "prod"

- name: Restart ddmail_openpgp_keyhandler gunicorn service
  ansible.builtin.service:
    name: ddmail_openpgp_keyhandler
    state: restarted
    enabled: true
  when: env == "prod"
