---
- name: Install sshd packages.
  apt:
    pkg:
      - openssh-server
    state: latest

- name: Create/edit sshd configuration file /etc/ssh/sshd_config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config

- name: Restar sshd Service
  service: name=ssh state=restarted enabled=yes
