---
name: python

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      ansible-lint:
        type: boolean
        default: false
      yamllint:
        type: boolean
        default: false

jobs:
  pip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ansible-lint
        run: ansible-lint
        if: ${{ inputs.ansible-lint }}

      - name: Run yamllint
        run: yamllint --format github .
        if: ${{ inputs.yamllint }}
